/**
 * A CDN/WAF refusal on the token exchange must never cost the user their
 * stored refresh token (chrischall/mcp-host#1015). The refusal page never
 * reached AlphaPortal's token endpoint, so nothing judged the token —
 * discarding it would force a needless re-capture of an 8-day credential
 * through the browser bridge. AlphaPortal's own JSON 401 still clears it.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { EdgeBlockedError } from '@chrischall/mcp-utils';
import { AlphaPortalClient } from '../src/client.js';
import { refreshAccessToken, RefreshTokenRejectedError } from '../src/auth.js';
import { registerHealthcheckTools } from '../src/tools/healthcheck.js';
import { createTestHarness, parseToolResult } from './helpers.js';

function jwt(exp: number): string {
  const b64 = (o: unknown) => Buffer.from(JSON.stringify(o)).toString('base64url');
  return `${b64({ alg: 'HS512' })}.${b64({ exp })}.sig`;
}
const FUTURE = Math.floor(Date.now() / 1000) + 3600;

const cloudfrontBlock = (status: 401 | 403) => () =>
  new Response(
    '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><HTML><HEAD><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
      `<H1>${status} ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">Request blocked. ` +
      "We can't connect to the server for this app or website at this time.<BR clear=\"all\">" +
      'Generated by cloudfront (CloudFront)<BR clear="all">Request ID: abc123==</BODY></HTML>',
    { status, headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront' } },
  );

const cloudflareChallenge = () =>
  new Response('<!DOCTYPE html><html><head><title>Just a moment...</title></head><body></body></html>', {
    status: 403,
    headers: { 'content-type': 'text/html', 'cf-mitigated': 'challenge', server: 'cloudflare' },
  });

/** AlphaPortal's OWN rejection — relayed by CloudFront, so it carries x-cache too. */
const alphaPortalJson401 = () =>
  new Response(JSON.stringify({ success: false, message: 'Invalid user!' }), {
    status: 401,
    headers: { 'content-type': 'application/json', 'x-cache': 'Error from cloudfront' },
  });

const BLOCKS: Array<[string, () => Response, RegExp]> = [
  ['a CloudFront 401 block page', cloudfrontBlock(401), /cloudfront/i],
  ['a CloudFront 403 block page', cloudfrontBlock(403), /cloudfront/i],
  ['a Cloudflare 403 challenge (cf-mitigated)', cloudflareChallenge, /cloudflare/i],
];

function storeWith(token: string) {
  const state = { stored: token as string | null, clears: 0 };
  const io = {
    load: () => state.stored,
    save: (_a: string, t: string) => { state.stored = t; },
    clear: () => { state.clears += 1; state.stored = null; },
  };
  return { state, io };
}

function fetchWith(refresh: () => Response) {
  return vi.fn(async (url: string) => {
    if (url.includes('/public/refresh-token')) return refresh();
    return new Response(JSON.stringify({ success: true, data: { Profile: {} } }), {
      status: 200,
      headers: { 'content-type': 'application/json' },
    });
  }) as unknown as typeof fetch;
}

describe('token refresh behind a CDN/WAF block', () => {
  beforeEach(() => {
    vi.stubEnv('ALPHAPORTAL_REFRESH_TOKEN', '');
    vi.stubEnv('ALPHAPORTAL_DISABLE_FETCHPROXY', '1');
  });
  afterEach(() => vi.unstubAllEnvs());

  for (const [label, block, vendor] of BLOCKS) {
    it(`refreshAccessToken throws EdgeBlockedError for ${label}`, async () => {
      const err = await refreshAccessToken('rt', fetchWith(block)).catch((e: unknown) => e);
      expect(err).toBeInstanceOf(EdgeBlockedError);
      expect(err).not.toBeInstanceOf(RefreshTokenRejectedError);
      expect((err as EdgeBlockedError).vendor).toMatch(vendor);
    });

    it(`keeps the stored refresh token on ${label}`, async () => {
      const token = jwt(FUTURE);
      const { state, io } = storeWith(token);
      const client = new AlphaPortalClient({ sessionIO: io, fetchImpl: fetchWith(block) });

      const err = await client.read('AlphaPortal/v1/user-students/list').catch((e: unknown) => e);
      expect(err).toBeInstanceOf(EdgeBlockedError);
      expect(state.clears, 'a block must not clear the store').toBe(0);
      expect(state.stored, 'the stored token must survive untouched').toBe(token);
      // Nor is it blacklisted in-process: the next call retries the same token.
      expect(client.hasStaticToken()).toBe(true);
    });

    it(`reports ${label} on the token exchange as edge_blocked`, async () => {
      const token = jwt(FUTURE);
      const { state, io } = storeWith(token);
      const client = new AlphaPortalClient({ sessionIO: io, fetchImpl: fetchWith(block) });
      const h = await createTestHarness((server) => registerHealthcheckTools(server, client));
      const res = await h.client.callTool({ name: 'alphaportal_healthcheck', arguments: {} });
      await h.close();
      const r = parseToolResult<{ ok: boolean; error?: { kind: string } }>(res as never);
      expect(r.ok).toBe(false);
      expect(r.error?.kind).toBe('edge_blocked');
      expect(state.stored).toBe(token);
    });
  }

  it("control: AlphaPortal's own JSON 401 still clears the stored token", async () => {
    const { state, io } = storeWith(jwt(FUTURE));
    const client = new AlphaPortalClient({ sessionIO: io, fetchImpl: fetchWith(alphaPortalJson401) });
    const err = await client.read('AlphaPortal/v1/user-students/list').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(RefreshTokenRejectedError);
    expect(state.clears).toBe(1);
    expect(state.stored).toBeNull();
  });

  it("control: AlphaPortal's own JSON 401 reads credential_rejected", async () => {
    const { io } = storeWith(jwt(FUTURE));
    const client = new AlphaPortalClient({ sessionIO: io, fetchImpl: fetchWith(alphaPortalJson401) });
    const h = await createTestHarness((server) => registerHealthcheckTools(server, client));
    const res = await h.client.callTool({ name: 'alphaportal_healthcheck', arguments: {} });
    await h.close();
    const r = parseToolResult<{ error?: { kind: string } }>(res as never);
    expect(r.error?.kind).toBe('credential_rejected');
  });
});
