import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { createTestHarness, parseToolResult } from './helpers.js';
import { AlphaPortalClient } from '../src/client.js';
import { nullSessionIO } from '../src/session.js';
import { registerHealthcheckTools } from '../src/tools/healthcheck.js';

interface Result {
  ok: boolean;
  credential: { source: string | null; resolved: boolean };
  probe: { url?: string; status?: number };
  error?: { kind: string; message: string; detail?: Record<string, unknown> };
  hint: string;
}

function jwt(exp: number): string {
  const b64 = (o: unknown) => Buffer.from(JSON.stringify(o)).toString('base64url');
  return `${b64({ alg: 'HS512' })}.${b64({ exp })}.sig`;
}
const FUTURE = Math.floor(Date.now() / 1000) + 3600;
const REFRESH_TOKEN = jwt(FUTURE);

const json = (status: number, body: unknown) =>
  new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });

// The page CloudFront serves when its WAF refuses a request — 403, HTML, and
// no word from the API behind it.
const CLOUDFRONT_403 = () =>
  new Response(
    '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><HTML><HEAD><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
      '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">Request blocked. ' +
      'We can\'t connect to the server for this app or website at this time.<BR clear="all">' +
      'Generated by cloudfront (CloudFront)<BR clear="all">Request ID: abc123==</BODY></HTML>',
    { status: 403, headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront' } },
  );

/** Route the refresh exchange and the profile probe to separate handlers. */
function fetchWith(handlers: { refresh?: () => Response; profile?: () => Response }) {
  return vi.fn(async (url: string) => {
    if (url.includes('/public/refresh-token')) {
      return (
        handlers.refresh?.() ??
        json(200, { success: true, data: { token: jwt(FUTURE), refreshToken: jwt(FUTURE) } })
      );
    }
    if (url.includes('/user/profile')) {
      return handlers.profile?.() ?? json(200, { success: true, data: { Profile: { UserName: 'p' } } });
    }
    return json(404, { success: false });
  }) as unknown as typeof fetch;
}

async function call(client: AlphaPortalClient): Promise<Result> {
  const h = await createTestHarness((server) => registerHealthcheckTools(server, client));
  const res = await h.client.callTool({ name: 'alphaportal_healthcheck', arguments: {} });
  await h.close();
  return parseToolResult<Result>(res as never);
}

const clientWith = (fetchImpl: typeof fetch, refreshToken: string | null = REFRESH_TOKEN) =>
  new AlphaPortalClient({ refreshToken: refreshToken ?? undefined, sessionIO: nullSessionIO, fetchImpl });

describe('alphaportal_healthcheck', () => {
  beforeEach(() => {
    vi.stubEnv('ALPHAPORTAL_REFRESH_TOKEN', '');
  });
  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it('is registered read-only and idempotent', async () => {
    const h = await createTestHarness((server) =>
      registerHealthcheckTools(server, clientWith(fetchWith({}))),
    );
    const tool = (await h.client.listTools()).tools.find((t) => t.name === 'alphaportal_healthcheck');
    await h.close();
    expect(tool?.annotations).toMatchObject({ readOnlyHint: true, idempotentHint: true });
  });

  it('reports ok and the source that actually resolved', async () => {
    const r = await call(clientWith(fetchWith({})));
    expect(r.ok).toBe(true);
    expect(r.credential).toMatchObject({ source: 'env-or-store', resolved: true });
    expect(r.probe.url).toBe('https://api.alpharoute.app/AlphaCore/v1/user/profile');
  });

  it("surfaces the resolver's guidance when nothing resolves, and does not probe", async () => {
    vi.stubEnv('ALPHAPORTAL_DISABLE_FETCHPROXY', '1');
    const fetchImpl = fetchWith({});
    const r = await call(clientWith(fetchImpl, null));
    expect(r.ok).toBe(false);
    expect(r.credential.resolved).toBe(false);
    expect(r.error?.kind).toBe('no_credential');
    expect(r.error?.message).toMatch(/ALPHAPORTAL_REFRESH_TOKEN/);
    // The capture one-liner is the only actionable part — it must survive.
    expect(r.error?.message).toMatch(/localStorage\.user/);
    expect(fetchImpl).not.toHaveBeenCalled();
  });

  it('reports a refresh token AlphaPortal rejects (401) as credential_rejected', async () => {
    const r = await call(
      clientWith(fetchWith({ refresh: () => json(401, { success: false, message: 'Unauthorized' }) })),
    );
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('credential_rejected');
    expect(r.hint).toMatch(/ALPHAPORTAL_REFRESH_TOKEN|alphaportal\.app/);
  });

  it('reports an access token the API rejects (401) as credential_rejected', async () => {
    const r = await call(clientWith(fetchWith({ profile: () => json(401, { message: 'nope' }) })));
    expect(r.error?.kind).toBe('credential_rejected');
  });

  it('tells an AlphaPortal-side failure (5xx) apart from a credential problem', async () => {
    const onProfile = await call(clientWith(fetchWith({ profile: () => json(502, { message: 'Bad gateway' }) })));
    expect(onProfile.error?.kind).toBe('http');
    expect(onProfile.probe.status).toBe(502);

    // A 5xx on the token exchange is transient too — never a rejected credential.
    const onRefresh = await call(clientWith(fetchWith({ refresh: () => json(503, { message: 'down' }) })));
    expect(onRefresh.error?.kind).toBe('http');
    expect(onRefresh.probe.status).toBe(503);
  });

  it('reports a CloudFront block page on the API as edge_blocked, not credential_rejected', async () => {
    const r = await call(clientWith(fetchWith({ profile: CLOUDFRONT_403 })));
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.error?.detail).toMatchObject({ vendor: expect.stringMatching(/cloudfront/i) });
  });

  it('reports a CloudFront block page on the token exchange as edge_blocked', async () => {
    const r = await call(clientWith(fetchWith({ refresh: CLOUDFRONT_403 })));
    expect(r.error?.kind).toBe('edge_blocked');
  });

  it('never reports the refresh token itself', async () => {
    const r = await call(clientWith(fetchWith({ refresh: () => json(401, {}) })));
    expect(JSON.stringify(r)).not.toContain(REFRESH_TOKEN);
    expect(JSON.stringify(r)).not.toContain(REFRESH_TOKEN.split('.')[1]);
  });
});
